#!/bin/bash

set -e

##############################################
# AO Bulk Export — Slack Completion Smoke Test (V3.3)
#
# Created by:
# Arham Dharewa
#
# Does NOT download files.
# Prompts for user / case / company / entity,
# then posts ONE Slack completion message.
##############################################

GREEN='\033[0;32m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
NC='\033[0m'

DEFAULT_ENTITY='Slack Smoke Test'
SUCCESS=1
SKIPPED=1
FAILED=1
TOTAL_FILES=3

SLACK_WEBHOOK_URL="${SLACK_WEBHOOK_URL:-https://hooks.slack.com/triggers/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}"

json_escape() {
    printf '%s' "$1" | sed -e 's/\\/\\\\/g' -e 's/"/\\"/g' -e 's/	/\\t/g' | awk '{printf "%s\\n", $0}' | sed 's/\\n$//'
}

notify_slack() {
    local msg="$1"
    local payload
    payload="{\"text\":\"$(json_escape "$msg")\"}"
    echo -e "${BLUE}Slack ← completion message${NC}"
    curl -sS -X POST \
        -H 'Content-type: application/json' \
        --data "$payload" \
        "$SLACK_WEBHOOK_URL"
    echo ""
}

echo -e "${CYAN}==========================================${NC}"
echo -e "${CYAN}AO Slack Completion Smoke Test V3.3${NC}"
echo -e "${CYAN}==========================================${NC}"
echo ""
echo -e "${BLUE}Enter run details${NC}"
echo ""

while [ -z "${USER_NAME:-}" ]; do
    read -r -p "User name: " USER_NAME
done
while [ -z "${CASE_ID:-}" ]; do
    read -r -p "Case ID: " CASE_ID
done
while [ -z "${COMPANY_NAME:-}" ]; do
    read -r -p "Company name: " COMPANY_NAME
done
while [ -z "${ENTITY_DIR:-}" ]; do
    read -r -p "Entity name [$DEFAULT_ENTITY]: " ENTITY_INPUT
    ENTITY_DIR="${ENTITY_INPUT:-$DEFAULT_ENTITY}"
done

if [ "$FAILED" -gt 0 ]; then
    TITLE_EMOJI=':warning:'
    ACTION_LINE=':warning: *Action needed:* one or more downloads failed — re-check before upload.'
else
    TITLE_EMOJI=':white_check_mark:'
    ACTION_LINE=''
fi

SLACK_MSG=$(cat <<EOF
*AO Bulk Export — Download Complete* ${TITLE_EMOJI}

*Run details*
• *User:* ${USER_NAME}
• *Case ID:* \`${CASE_ID}\`
• *Company:* ${COMPANY_NAME}
• *Entity:* ${ENTITY_DIR}

*Results*
• :large_green_circle: Successful: ${SUCCESS}
• :large_yellow_circle: Skipped: ${SKIPPED}
• :red_circle: Failed: ${FAILED}
• :file_folder: Files attempted: ${TOTAL_FILES}
• :open_file_folder: Download folder: \`${ENTITY_DIR}\`
${ACTION_LINE:+
${ACTION_LINE}
}
*Next step*
@acc-ops-seniors, please review the files before uploading.

_Generated by AO Bulk Export Download Script Generator V3.3 · Created by Arham Dharewa_
EOF
)

echo ""
echo -e "${BLUE}Preview:${NC}"
echo "$SLACK_MSG"
echo ""

notify_slack "$SLACK_MSG"

echo ""
echo -e "${GREEN}Smoke test complete. Check Slack for one completion message.${NC}"
